#! /bin/sh

# kill programs
killall -q dunst
killall -q picom
killall -q sxhkd
killall -q polybar
killall -q xsetroot

while pfrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pfrep -u $UID -x picom >/dev/null; do sleep 1; done
while pfrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pfrep -u $UID -x fehbg >/dev/null; do sleep 1; done
while pfrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pfrep -u $UID -x xsetroot >/dev/null; do sleep 1; done

# autostart apps
xrdb -merge ~/.Xresources &
dunst & 
picom & 
sxhkd &
~/.config/polybar/launch.sh
# xsetroot -cursor_name left_pto
~/.fehbg
setxkbmap latam
wmname LG3D
# see https://unix.stackexchange.com/a/295652/332452
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# see https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# see https://github.com/NixOS/nixpkgs/issues/14966#issuecomment-520083836
mkdir -p "$HOME"/.local/share/keyrings

# colors
NORMAL_BORDER_COLOR="#0e0c17"
ACTIVE_BORDER_COLOR="#262734"
FOCUSED_BORDER_COLOR="#585767"
PRESEL_FEEDBACK_COLOR="#D6A36A"

bspc monitor -d I II III IV V 

bspc config border_width          1
bspc config window_gap            8
Bspc config normal_border_color   "$NORMAL_BORDER_COLOR"
bspc config active_border_color   "$ACTIVE_BORDER_COLOR"
bspc config focused_border_color  "$FOCUSED_BORDER_COLOR"
bspc config presel_feedback_color "$PRESEL_FEEDBACK_COLOR"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
